---
sudo: required
dist: trusty

language: generic

env:
  - ANSIBLE_VERSION="1.9"
  - ANSIBLE_VERSION="2.0"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - sudo -H pip install "ansible~=$ANSIBLE_VERSION"

  - sudo ansible-galaxy install bbatsche.Base

  - echo localhost ansible_connection=local ansible_ssh_user=$USER > inventory

  - travis_wait ansible-playbook -i inventory provision-playbook.yml

  - "echo #!/bin/sh >> play.sh"
  - echo sudo su $USER -c \'ansible-playbook -i inventory travis-playbook.yml\' >> play.sh
  - chmod +x play.sh
script:
  # Syntax check
  - ansible-playbook -i inventory travis-playbook.yml --syntax-check

  # Play test
  - travis_wait ./play.sh

  # Idempotence test
  - ./play.sh > idempotence.out
  - >
    grep -q "changed=0.*failed=0" idempotence.out
    && (echo "Idempotence test: pass" && exit 0) || (echo "Idempotence test: fail" && cat idempotence.out && exit 1)

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
