---
- hosts: all
  remote_user: root
  become: yes

  vars_files:
    - defaults/main.yml
  vars:
    domain: test.dev
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
