---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    domain: test.dev

  roles:
    - bbatsche.Base

  tasks:
    - include: tasks/main.yml

  handlers:
    - include: handlers/main.yml
