---
- hosts: all

  vars_files:
    - defaults/main.yml
    - vars/main.yml

  vars:
    domain: test.dev

  tasks:
    - import_tasks: tasks/main.yml

  handlers:
    - import_tasks: handlers/main.yml
