---
- hosts: all
  remote_user: root
  become: true
  vars_files:
  - defaults/main.yml
  vars:
    domain: test.dev
  roles:
  - bbatsche.Base
  tasks:
  - include: tasks/main.yml
  handlers:
  - include: handlers/main.yml
  - name: Restart Nginx
    service: name=nginx state=restarted
    become: true
  - name: Restart Passenger App
    command: passenger-config restart-app {{ http_root }}/{{ domain }} --ignore-app-not-running
    when: site_type in ['node', 'python', 'ruby']
