---
- hosts: all
  remote_user: root
  become: yes

  vars_files:
    - defaults/main.yml
  vars:
    domain: test.dev
  tasks:
    - include: tasks/main.yml
  handlers:
    - include: handlers/main.yml
    # same handlers as above
    - name: Restart Nginx
      service: name=nginx state=restarted
      become: yes

    - name: Restart Passenger App
      command: passenger-config restart-app {{ http_root }}/{{ domain }} --ignore-app-not-running
      when: site_type in ['node', 'python', 'ruby']
