---
- name: Add Let's Encrypt APT Repository
  apt_repository: repo=ppa:certbot/certbot state=present
  become: yes

- name: Install Let's Encrypt
  apt: name=python-certbot-nginx state=present
  become: yes

- name: Create Let's Encrypt Web Root
  file: path={{ http_root }}/letsencrypt state=directory
  become: yes

# Need to make sure the main Nginx config has been loaded before attempting to request the cert
- name: Restart Nginx
  meta: flush_handlers

- name: Generate Certificate for {{ domain }}
  command: certbot certonly -n --agree-tos -m {{ email_address }} {{ "--staging" if env_name == "dev" else "" }} --webroot -w {{ http_root }}/letsencrypt -d {{ domain }},www.{{ domain }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}/fullchain.pem
  become: yes

- name: Modify Let's Encrypt Webroot Config
  lineinfile:
    name:     /etc/letsencrypt/renewal/{{ domain }}.conf
    regexp:   '^{{ item }}\s*=\s*.+(,?)$'
    line:     '{{ item }} = {{ http_root }}/{{ domain }}/public\1'
    backrefs: yes
  loop:
    - webroot_path
    - www.{{ domain }}
    - "{{ domain }}"
  become: yes

- name: Create Let's Encrypt Cron Job
  cron:
    day:    "*/12"
    hour:   "3"
    minute: "15"
    name:   Renew Let's Encrypt Certs
    job:    /usr/bin/certbot renew --quiet
  become: yes
