---
- name: Add Phusion Passenger APT Key
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7 state=present
  become: yes

- name: Add Phusion Passenger APT Repository
  apt_repository:
    repo: "deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main"
    state: present
  become: yes

- name: Install
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - nginx-extras
    - passenger

- name: Copy HTML5 Boilerplate Configs
  copy: src=h5bp dest=/etc/nginx/
  become: yes
  notify: Restart Nginx

- name: Create Default Site
  copy: src=site.default.conf dest=/etc/nginx/sites-available/default mode=0600
  become: yes
  notify: Restart Nginx

- name: Propogate Web Admin Group in Sites-Available
  file:
    path: /etc/nginx/sites-available
    state: directory
    owner: root
    group: web-admin
    mode: 02775
  become: yes

- name: Allow Web Admins to Write Sites-Available
  acl:
    name: /etc/nginx/sites-available
    etype: group
    entity: web-admin
    permissions: rwx
    state: present
  become: yes

- name: Enable Default Site
  file:
    src:   /etc/nginx/sites-available/default
    dest:  /etc/nginx/sites-enabled/default
    state: link
  become: yes
  notify: Restart Nginx

- name: Create Log Directory
  file: path=/var/log/nginx state=directory mode=0755 owner=www-data group=www-data
  become: yes

- name: Create Main Coniguration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  become: yes
  notify: Restart Nginx

- name: Copy HTML5 Boilerplate Main Config
  template: src=h5bp.conf.j2 dest=/etc/nginx/h5bp/basic.conf
  become: yes
  notify: Restart Nginx

- name: Copy mime.types
  file: src=mime.types dest=/etc/nginx/mime.types
  become: yes
  notify: Restart Nginx

- name: Create HTTP Root
  file: path={{ http_root }} state=directory mode=02775
  become: yes

# If HTTP root is an NFS mount we need to skip various ACL and permission related tasks
# Disable warnings since Ansible's stat module doesn't return any info about the FS type
- name: Check if HTTP Root is NFS
  command: stat -f -c %T {{ http_root }} warn=no
  register: http_root_fs
  changed_when: no

- include: http_root_acl.yml
  when: >
    not (
      http_root_fs.stdout == "nfs" or
      http_root_fs.stdout == "vmhgfs" or
      http_root_fs.stdout == "vboxsf" or
      http_root_fs.stdout == "prl_fs" or
      http_root_fs.stdout == "fuseblk"
    )

- include: site.yml
  when: domain is defined
