---
- name: Create Site Directory
  file:
    path:  "{{ http_root }}/{{ domain }}"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: www-data
    mode:  02755
  register: dir_create_result
  failed_when: >
    dir_create_result.state != "directory" or
    (dir_create_result.msg is defined and dir_create_result.msg != "chown failed")
  become: yes

- name: Create Public Directory
  file:
    path:  "{{ http_root }}/{{ domain }}/public"
    state: directory
    owner: "{{ ansible_ssh_user }}"
    group: www-data
    mode:  02755
  register: dir_create_result
  failed_when: >
    dir_create_result.state != "directory" or
    (dir_create_result.msg is defined and dir_create_result.msg != "chown failed")
  become: yes

- name: Copy Site Config
  template:
    src:   site.conf.j2
    dest:  /etc/nginx/sites-available/{{ domain }}
    owner: "{{ ansible_ssh_user }}"
    group: www-data
    mode:  0640
  become: yes
  notify:
    - Restart Nginx
    - Restart Passenger App

- name: Activate Site
  file:
    src:   /etc/nginx/sites-available/{{ domain }}
    dest:  /etc/nginx/sites-enabled/{{ domain }}
    state: link
  become: yes
  notify:
    - Restart Nginx
    - Restart Passenger App

- name: Create Site Log Directory
  file:
    path:  /var/log/nginx/{{ domain }}
    state: directory
    owner: www-data
    group: www-data
    mode:  0755
  become: yes

- name: Copy index.html
  template:
    src: index.html.j2
    dest: "{{ http_root }}/{{ domain }}/public/index.html"
  when: copy_index
