---
- include: letsencrypt.yml
  static: no
  when:
    - use_ssl
    - use_letsencrypt

# Either we are in production with a typical flat filesystem, or Vagrant with a shared folder structure
# If it's vagrant, we assume the user has the user/group configured correctly, we just manage perms
- name: Create Site Directory
  file: path={{ http_root }}/{{ domain }} state=directory mode=02775
  become: yes

- name: Create Public Directory
  file: path={{ http_root }}/{{ domain }}/public state=directory mode=02775
  become: yes

- name: Copy Site Config
  template:
    src:   site.conf.j2
    dest:  /etc/nginx/sites-available/{{ domain }}
    owner: root
    group: web-admin
    mode:  0660
  become: yes
  notify:
    - Restart Nginx
    - Restart Passenger App

- name: Activate Site
  file:
    src:   /etc/nginx/sites-available/{{ domain }}
    dest:  /etc/nginx/sites-enabled/{{ domain }}
    state: link
  become: yes
  notify:
    - Restart Nginx
    - Restart Passenger App

- name: Create Site Log Directory
  file:
    path:  /var/log/nginx/{{ domain }}
    state: directory
    owner: www-data
    group: www-data
    mode:  0750
  become: yes

- name: Copy index.html
  template:
    src: index.html.j2
    dest: "{{ http_root }}/{{ domain }}/public/index.html"
  when: copy_index

- name: Add Domain to Hosts File
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ domain }}"
    unsafe_writes: "{{ ansible_connection == 'docker' }}"
  become: yes
