---
- name: Configure Let's Encrypt
  include_tasks: letsencrypt.yml
  when: use_letsencrypt

- name: Configure Self Signed Certificate
  block:
    - name: Generate Certificate Signing Request
      openssl_csr:
        path:                   /etc/nginx/certs/{{ domain }}.csr
        privatekey_path:        /etc/nginx/certs/default.key
        common_name:            "{{ domain }}"
        subject_alt_name:       "DNS:{{ domain }},DNS:www.{{ domain }}"
        country_name:           "{{ country_name | default(omit) }}"
        state_or_province_name: "{{ state_name | default(omit) }}"
        locality_name:          "{{ locality_name | default(omit) }}"
        organization_name:      "{{ org_name | default(omit) }}"
        email_address:          "{{ email_address }}"
      become: yes

    - name: Generate Self Signed Certificate
      openssl_certificate:
        path:            /etc/nginx/certs/{{ domain }}.crt
        privatekey_path: /etc/nginx/certs/default.key
        csr_path:        /etc/nginx/certs/{{ domain }}.csr
        provider:        selfsigned
      become: yes
      notify: Restart Nginx
      register: ssl_cert_generated
  when: not use_letsencrypt
