---
- name: Install Python / OpenSSL Libraries
  apt:
    name:
      - "{{ 'python3-pip' if ansible_python.version.major == 3 else 'python-pip' }}"
      - "{{ 'python3-dev' if ansible_python.version.major == 3 else 'python-dev' }}"
      - libssl-dev
      - libffi-dev
    state: present
  become: yes

# Switch these two to apt version after support for Trusty drops
- name: Update Setuptools
  pip: name=setuptools version={{ setuptools_version }}
  become: yes
- name: Install PyOpenSSL
  pip:
    name:
      - cffi
      - ipaddress
      - enum34
      - pyopenssl
    state: latest # make sure Trusty updates pyOpenSSL
  become: yes

- name: Create CSR Directory
  file:
    name: /etc/ssl/csr
    state: directory
    mode: 0755
  become: yes

- name: Create OpenSSL Private Key
  openssl_privatekey:
    path: /etc/nginx/certs/default.key
    size: "{{ privatekey_bits }}"
  become: yes

- name: Generate Certificate Signing Request
  openssl_csr:
    path:                   /etc/nginx/certs/default.csr
    privatekey_path:        /etc/nginx/certs/default.key
    common_name:            "{{ ansible_fqdn }}"
    country_name:           "{{ country_name | default(omit) }}"
    state_or_province_name: "{{ state_name | default(omit) }}"
    locality_name:          "{{ locality_name | default(omit) }}"
    organization_name:      "{{ org_name | default(omit) }}"
    email_address:          "{{ email_address }}"
  become: yes

- name: Generate Self Signed Certificate
  openssl_certificate:
    path:            /etc/nginx/certs/default.crt
    privatekey_path: /etc/nginx/certs/default.key
    csr_path:        /etc/nginx/certs/default.csr
    provider:        selfsigned
  become: yes
  notify: Restart Nginx

- name: Generate DH Params
  openssl_dhparam:
    path: /etc/ssl/certs/dhparam.pem
    size: "{{ dhparam_bits }}"
  become: yes
  notify: Restart Nginx

- name: Copy SSL Coniguration
  template:
    src:  ssl.conf.j2
    dest: /etc/nginx/conf.d/ssl.conf
  become: yes
  notify: Restart Nginx
