---
- name: Restart Nginx
  service: name=nginx state=restarted
  become: yes

- name: Restart Passenger App
  command: passenger-config restart-app {{ http_root }}/{{ domain }} --ignore-app-not-running
  when: passenger_app or site_type in ['python', 'ruby']
