---
- name: Restart Nginx
  service: name=nginx state=restarted
  become: yes

- name: Restart Passenger App
  command: passenger-config restart-app {{ http_root }}/{{ domain }} --ignore-app-not-running
  when: site_type in ['node', 'python', 'ruby']
