---
- name: Restart Nginx
  service: name=nginx state=restarted
  become: yes

- name: Restart Passenger App
  command: >-
    passenger-config restart-app {{ http_root }}/{{ domain }} --ignore-app-not-running
    {{ "--ignore-passenger-not-running" if ansible_connection | default('smart') == 'docker' else "" }}
  when: passenger_app
