---
- hosts: all

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml

  pre_tasks:
    - name: Clear index.html for test
      file:
        name: "{{ http_root }}/{{ domain }}/public/index.html"
        state: absent
      when: domain | default('') != ''

  tasks:
    - include: ../../tasks/main.yml

  post_tasks:
    - name: Create Test Assets
      file:
        name: "{{ http_root }}/{{ domain }}/public/{{ item }}"
        state: touch
      when: domain | default('') != ''
      with_items:
        - test.js
        - test.css
        - test.jpg

  handlers:
    - include: ../../handlers/main.yml
