---
- hosts: all

  vars_files:
    - ../../defaults/main.yml
    - ../../vars/main.yml

  pre_tasks:
    - name: Clear index.html for test
      file:
        name: "{{ http_root }}/{{ domain }}/public/index.html"
        state: absent
      when: domain | default('') != ''

  tasks:
    - include: ../../tasks/main.yml

  post_tasks:
    - name: Create Test Assets
      file:
        name: "{{ http_root }}/{{ domain }}/public/{{ item }}"
        state: touch
      when: domain | default('') != ''
      with_items:
        - test.js
        - test.css
        - test.jpg

    # Ansible's service module doesn't play well with Docker, so for testing just manually restart
    - name: Force Nginx Restart
      command: service nginx restart warn=no
      become: yes
      when: ansible_connection | default('smart') == 'docker'

  handlers:
    - include: ../../handlers/main.yml
