---
- hosts: all
  vars_files:
    - ../../defaults/main.yml
  pre_tasks:
    - name: Clear index.html for test
      file:
        name: "{{ http_root }}/{{ domain }}/public/index.html"
        state: absent
      when: domain | default('') != ''
  tasks:
    - include: ../../tasks/main.yml
  handlers:
    - include: ../../handlers/main.yml
    # same handlers as above
    - name: Restart Nginx
      service: name=nginx state=restarted
      become: yes

    - name: Restart Passenger App
      command: passenger-config restart-app {{ http_root }}/{{ domain }} --ignore-app-not-running
      when: site_type in ['node', 'python', 'ruby']
